apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gameserver
  template:
    metadata:
      labels:
        name: gameserver
    spec:
      serviceAccountName: gameserver
      containers:
        - name: gameserver
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - gameserver
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gameserver"
