kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gameserver
subjects:
- kind: ServiceAccount
  name: gameserver
roleRef:
  kind: Role
  name: gameserver
  apiGroup: rbac.authorization.k8s.io
